### ISSUE TITLE
Uncaught UnexpectedValueException: responseType is not "id-pkix-ocsp-basic"

### ISSUE THREAD

**Issue by jakenoble** [hoels/app-store-server-library-php#8] opened 2024-09-03 08:49 UTC
Today I started getting the following error, out of the blue. Does anyone have any idea about this? Googling has turned out nothing.

```
Fatal error: Uncaught UnexpectedValueException: responseType is not "id-pkix-ocsp-basic" but is  in vendor/web-eid/ocsp-php/src/OcspResponse.php:66
Stack trace:
#0 vendor/web-eid/ocsp-php/src/OcspResponse.php(137): web_eid\ocsp_php\OcspResponse->getBasicResponse()
#1 vendor/hoels/app-store-server-library-php/src/AppStoreServerLibrary/ChainVerifier.php(239): web_eid\ocsp_php\OcspResponse->validateCertificateId(Array)
#2 vendor/hoels/app-store-server-library-php/src/AppStoreServerLibrary/ChainVerifier.php(169): AppStoreServerLibrary\ChainVerifier->checkOcspStatus(Object(AppStoreServerLibrary\X509\Certificate), Object(AppStoreServerLibrary\X509\Certificate), Object(AppStoreServerLibrary\X509\Certificate))
#3 vendor/hoels/app-store-server-library-php/src/AppStoreServerLibrary/ChainVerifier.php(112): AppStoreServerLibrary\ChainVerifier->verifyChain(Object(AppStoreServerLibrary\X509\Certificate), Object(AppStoreServerLibrary\X509\Certificate), true, Object(DateTime))
#4 vendor/hoels/app-store-server-library-php/src/AppStoreServerLibrary/SignedDataVerifier.php(158): AppStoreServerLibrary\ChainVerifier->verify('eyJhbGciOiJFUzI...', true, Object(AppStoreServerLibrary\Models\Environment))
#5 vendor/hoels/app-store-server-library-php/src/AppStoreServerLibrary/SignedDataVerifier.php(86): AppStoreServerLibrary\SignedDataVerifier->decodeSignedObject('eyJhbGciOiJFUzI...')
#6 public/notifications/ios/production/index.php(70): AppStoreServerLibrary\SignedDataVerifier->verifyAndDecodeNotification('eyJhbGciOiJFUzI...')
#7 {main}
  thrown in vendor/web-eid/ocsp-php/src/OcspResponse.php on line 66
```

**Comment by hoels** [comment] 2024-09-03 17:11
Hey Jake,
the exception is thrown because of an error in our dependency [web-eid/ocsp-php](https://github.com/web-eid/ocsp-php). There must have been a change in the OCSP response from Apple leading to this issue even without any changes in the code. The quickest fix right now is to disable online checks when using the `SignedDataVerifier`. I would usually not recommend doing this, but until I found time to look into the issue, that's how to get your code working again for now.

**Comment by jakenoble** [comment] 2024-09-04 07:32
Thanks, @hoels - that has sorted it for now. Rather oddly, I have yet to find any other reports of this. Perhaps it was a temporary issue and not a change by apple 🤷

**Comment by b-lester** [comment] 2024-09-04 14:28
I also started getting this exception. I disabled online checks as @hoels suggested which fixed the issue for now. Is there a fix for this coming since it is not recommended to operate without online checks? Or is it a temporary issue that will "fix itself" once Apple fixes their response?

**Comment by LukasB-DEV** [comment] 2024-09-10 10:32
I had the same problem. I fixed it temporarily by deactivating the online checks. When will there be a solution to this problem?

**Comment by hoels** [comment] 2024-09-10 17:26
Thanks for your reports. Unfortunately, I haven‘t found time to look into this yet. Since the issue lies in another library, I have to find out what‘s going on there, how to fix it and then either hope the maintainers of the other library will quickly merge my fix or create a fork of the library. I cannot estimate the effort right now, but since I‘m affected by this myself, I will definitely look into this as soon as I can and keep you updated.

**Comment by hoels** [comment] 2024-09-12 21:37
**I have just released a new version that fixes the OCSP issue. After updating to the newest version, you can enable online checks again.**

For anyone with technical interest: The exception was thrown because the Apple OCSP response returns `malformedRequest` as the `responseStatus`. This means that the issue was not a change in the response format but a change in the validation of the OCSP request on Apple’s side.

The DER-encoded OCSP request constructed by the _web-eid/ocsp-php_ library always contains an object for the `requestExtensions`. Since we do not currently add a nonce extension, this array was empty but still led to an additional object in the sequence. This seems to be previously allowed but is now considered malformed. The solution is to add this array to the OCSP request only when an actual value is added to it.

Another difference I observed between our OCSP request and the one constructed in the Python library is that the _web-eid/ocsp-php_ library always uses the SHA1 algorithm for the issuer name/key hashes, while the Python Cryptography module allows to pick an algorithm and SHA256 is selected by the Apple App Store Server Library. This does not seem to be an issue (yet), but since SHA1 is insecure and increasingly phased out, I also switched the algorithm.

To implement the changes, I copied 2 classes from the _web-eid/ocsp-php_ library into this library. I will also create pull requests in the _web-eid/ocsp-php_ to fix it there. For the future it might make sense to replace the _web-eid/ocsp-php_ library. However, there aren’t any good solutions yet and I would have to build one myself, which I currently don’t have time for.

But for now I’m glad the issue could be fixed without a lot of effort. Please let me know if you still experience any issues. Thanks for your patience!

**Closed as completed by hoels** 2024-09-12 21:37 UTC

**Comment by b-lester** [comment] 2024-09-12 22:54
@hoels thanks for the explanation. I've updated and I can confirm that the fix is working. Cheers.

**Comment by jakenoble** [comment] 2024-09-26 10:23
This has just occurred for me again, `responseType is not "id-pkix-ocsp-basic"`

**Comment by hoels** [comment] 2024-09-26 17:33
@jakenoble I cannot verify this on my side. Everything is working fine for me. Could you please check again that your version is up-to-date and you are importing the correct Apple root certificates?

**Comment by LukasB-DEV** [comment] 2024-09-26 17:43
I can verify that it still works for me

**Comment by jakenoble** [comment] 2024-09-26 18:35
Thanks @hoels and @LukasB-DEV - I shall retry and check again. Strange that I get this error again, out of the blue 2 days after updating and re-enabling online checks 🤔
